
class ENDPOINTS:
    SHORTENED_URL = "/v2/shortened-urls/"
    SMS_BROADCAST_CREATE = "/v2/sms_broadcast/create/"
    CAMPAIGN_AGENT_LIVE = "/v2/campaign/agent/live/"
    MEDIA = "/v2/media/"
    GET_AREA_CODE = "/v2/get_area_code/"
    AUTO_UNRENT_SETTINGS = "/v2/auto_unrent/settings/"
    SMS_NUMBER_SHOW_RENTED_NUMBER = "/v2/sms_number/show_rented_number/"
    VALIDATED_AND_RENTED_NUMBERS = "/v2/validated_and_rented_numbers/"
    SMS_RENT_NUMBER = "/v2/sms_number/sms_rent_number/"
    P2P_CAMPAIGN = "/v2/sms_campaign/snowflake/"
    COLLECTIVE_TEXTING = "/v2/collective_texting/"
    COLLECTIVE_TEXTING_AGENTS = COLLECTIVE_TEXTING + "{campaign_id}/agents/"
    COLLECTIVE_TEXTING_AGENTS_ADD = COLLECTIVE_TEXTING + "{campaign_id}/agents/add/"
    COLLECTIVE_TEXTING_AGENTS_REASSIGN = COLLECTIVE_TEXTING + "{campaign_id}/agents/reassign/"
    P2P_CAMPAIGN_SURVEY_LIST = "/v2/sms_campaign/snowflake/survey-list/"
    CREDITS_USAGE = "/v2/credits_usage/"
    TAGS = "/v2/tags/"
    CONTACTS = "/v2/contacts/"
    CONTACT_TAGGINGS = CONTACTS + "{contact_id}/taggings/"
    SMS_BROADCAST = "/v2/sms_broadcast/"

    # V1 Endpoints
    AGENTS = "/v1/agents/"
    CALL_CENTER_CAMPAIGNS = "/v1/callcenter_campaigns/"
    CAMPAIGNS = "/v1/campaigns/"
    CONTACTS_V1 = "/v1/contacts/"
    CUSTOM_FIELDS = "/v1/custom_fields/"
    DNC_CONTACTS = "/v1/dnc_contacts/"
    DNC_LISTS = "/v1/dnc_lists/"
    INTEGRATION_FIELDS = "/v1/integration_fields/"
    NUMBERS = "/v1/numbers/"
    NUMBER_RENT_RATES = "/v1/number_rent_rates/"
    P2P_CAMPAIGNS = "/v1/p2p_campaigns/"
    PHONEBOOKS = "/v1/phonebooks/"
    POWER_CAMPAIGN = "/v1/power_campaign/"
    QUESTIONS = "/v1/questions/"
    REVALIDATE_NUMBERS = "/v1/revalidate_numbers/"
    SMS_CAMPAIGNS = "/v1/sms_campaigns/"
    TAGS_V1 = "/v1/tags/"
    TEAMS = "/v1/teams/"
    TEMPLATES = "/v1/templates/"
    USERS = "/v1/users/"
    VB_CAMPAIGN = "/v1/vb_campaign/"
    VB_TEMPLATES = "/v1/vb_templates/"
    VOICE_BROADCASTS = "/v1/voice_broadcasts/"
    WEBHOOKS = "/v1/webhooks/"
    SMS_CAMPAIGN_REPORT_EXPORT = "/v1/sms_campaign/sms_report/export/"
    CONTACTS_BULK_CREATE = "/v1/contacts/bulk_create/"
    CONTACTS_FIELDS = "/v1/contacts/fields/"
    RELATIONAL_CAMPAIGN = "/email/v1/relational-campaign/"

